deployments:
  default:
    dockerimage: ubuntu
    port_forwarding: 80:3000
    copy_files:
      - ~/.ssh/id_rsa ~/code/id_rsa
      - ~/.ssh/id_rsa.pub ~/code/id_rsa.pub
    build_steps:
      - >
        DEBIAN_FRONTEND=noninteractive apt-get update &&
        DEBIAN_FRONTEND=noninteractive apt-get -y install 
        ruby-full gnupg wget ruby-bundler curl git sudo 
        build-essential mongodb xvfb firefox gettext-base
      - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      - >
        DEBIAN_FRONTEND=noninteractive apt-get update &&
        DEBIAN_FRONTEND=noninteractive apt-get -y install nodejs
      - npm install -g testcafe
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - apt-get install -y ./google-chrome-stable_current_amd64.deb
      - apt-get clean && rm -rf /var/lib/apt/lists/*
      - mkdir ~/.ssh
      - cp /code/id_rsa* ~/.ssh
      - chmod 400 ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa.pub
      - squash-cmd--git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
      - squash-cmd--git clone git@github.com:wisedrette/django-react-front.git -b {SQUASH_GIT_MATCH_BRANCH} --single-branch /code/frontend
      - cd /code
      - bundle install
      - cd /code/frontend
      - npm install
    post_build_steps:
      - cd /code
      - bundle install
      - cd /code/frontend
      - npm install
    launch_steps:
      - service mongodb start
      - cd /code
      - bundle exec ruby app.rb &
      - cd /code/frontend
      - npm start
    deployment_page_commands:
      tests:
        - cd /code/frontend
        - bash launch_tests.sh
      testcafe:
        - xvfb-run testcafe --skip-js-errors firefox,chrome test.js
    pipelines:
      - testcafe:
          scripts:
            - cd /code/frontend
            - xvfb-run testcafe --skip-js-errors firefox,chrome test.js
    run_options: -p 4567:4567
    subdomain_port_mapping:
      - api:4567
